/**
 * @module types
 * Core type definitions for the @imgbt/core SDK.
 */

/**
 * Configuration options for the Imgbt client.
 *
 * @example
 * ```typescript
 * const imgbt = new Imgbt({
 *   apiKey: 'pk_live_xxx',
 *   vault: 'my-vault',
 *   defaultDomain: 'assets.myapp.com',
 *   timeout: 60_000,
 *   maxRetries: 5,
 * })
 * ```
 */
export interface ImgbtOptions {
  /**
   * Your imgbt API key. Starts with `pk_` (public) or `sk_` (secret).
   * Falls back to the `IMGBT_API_KEY` environment variable if not provided.
   *
   * @example 'pk_live_abc123'
   */
  apiKey?: string

  /**
   * The vault slug to operate against. Every API request is scoped to this vault.
   * Falls back to the `IMGBT_VAULT` environment variable if not provided.
   *
   * @example 'my-saas-vault'
   */
  vault?: string

  /**
   * Base URL for the imgbt API. Defaults to `https://api.imgbt.com/v1`.
   * Override for testing or custom deployments.
   *
   * @default 'https://api.imgbt.com/v1'
   * @example 'http://localhost:8787/v1'
   */
  baseUrl?: string

  /**
   * Default delivery domain for URL generation. When set, `imgbt.url()` and
   * `imgbt.signUrl()` use this domain instead of the vault subdomain.
   *
   * @example 'assets.myapp.com'
   */
  defaultDomain?: string

  /**
   * Request timeout in milliseconds. Applied to every API request.
   * Set to `0` to disable timeouts.
   *
   * @default 30000
   */
  timeout?: number

  /**
   * Maximum number of retry attempts for failed requests (429 and 5xx only).
   * Uses exponential backoff with jitter.
   *
   * @default 3
   */
  maxRetries?: number
}

/**
 * Represents a stored asset in imgbt. Returned by upload, get, update, and list operations.
 *
 * @example
 * ```typescript
 * const asset = await imgbt.get('asset_01HQ3...')
 * console.log(asset.url)        // delivery URL
 * console.log(asset.filename)   // original filename
 * console.log(asset.size)       // file size in bytes
 * ```
 */
export interface Asset {
  /** Unique asset identifier, e.g. `asset_01HQ3...` */
  id: string

  /** Vault this asset belongs to */
  vault: string

  /**
   * Top-level organizational key. Typically a tenant or company identifier.
   * @example 'acme-corp'
   */
  partition: string

  /**
   * Second-level organizational key. Typically a department, feature, or category.
   * @example 'sf-office'
   */
  collection: string

  /**
   * Third-level organizational key. Typically a sub-category or content type.
   * @example 'avatars'
   */
  channel: string

  /**
   * Original filename of the uploaded asset.
   * @example 'jane.png'
   */
  filename: string

  /** Full delivery URL for the asset */
  url: string

  /**
   * Hierarchical path: `{partition}/{collection}/{channel}/{filename}`
   * @example 'acme-corp/sf-office/avatars/jane.png'
   */
  path: string

  /** MIME content type of the asset */
  contentType: string

  /** File size in bytes */
  size: number

  /** Width in pixels (images only) */
  width?: number

  /** Height in pixels (images only) */
  height?: number

  /** Number of pages (PDFs only) */
  pages?: number

  /** User-defined metadata key/value pairs */
  metadata: Record<string, string>

  /** User-defined tags for categorisation */
  tags: string[]

  /** ISO 8601 timestamp when the asset was uploaded */
  createdAt: string

  /** ISO 8601 timestamp when the asset was last modified */
  updatedAt: string
}

/**
 * Options for uploading a file to imgbt.
 *
 * @example
 * ```typescript
 * const asset = await imgbt.upload({
 *   file: fileBuffer,
 *   partition: 'acme-corp',
 *   collection: 'sf-office',
 *   channel: 'avatars',
 *   filename: 'jane.png',
 *   metadata: { userId: '123' },
 *   tags: ['profile', 'employee'],
 * })
 * ```
 */
export interface UploadOptions {
  /**
   * The file data to upload. Accepts a Uint8Array (including Node.js Buffer),
   * Blob, File, ReadableStream, or ArrayBuffer.
   */
  file: Uint8Array | Blob | ReadableStream | ArrayBuffer | File

  /**
   * Top-level organizational key. Required.
   * @example 'acme-corp'
   */
  partition: string

  /**
   * Second-level organizational key. Required.
   * @example 'sf-office'
   */
  collection: string

  /**
   * Third-level organizational key. Required.
   * @example 'avatars'
   */
  channel: string

  /**
   * Optional filename. If omitted, a unique filename is auto-generated by the server.
   * @example 'jane.png'
   */
  filename?: string

  /**
   * Optional MIME content type. The server will attempt to detect the content
   * type from the file data if not provided.
   * @example 'image/png'
   */
  contentType?: string

  /**
   * Optional user-defined metadata key/value pairs stored alongside the asset.
   * @example { userId: '123', source: 'upload-widget' }
   */
  metadata?: Record<string, string>

  /**
   * Optional list of tags for easy categorisation and filtering.
   * @example ['profile', 'employee']
   */
  tags?: string[]
}

/**
 * Options for listing assets. All filters are optional and can be combined.
 *
 * @example
 * ```typescript
 * // List all avatars for a specific tenant
 * const result = await imgbt.list({
 *   partition: 'acme-corp',
 *   collection: 'sf-office',
 *   channel: 'avatars',
 *   limit: 50,
 * })
 *
 * // Use auto-pagination
 * for await (const asset of imgbt.list({ partition: 'acme-corp' })) {
 *   console.log(asset.filename)
 * }
 * ```
 */
export interface ListOptions {
  /**
   * Filter by partition (top-level key).
   * @example 'acme-corp'
   */
  partition?: string

  /**
   * Filter by collection (second-level key). Requires `partition` to also be set.
   * @example 'sf-office'
   */
  collection?: string

  /**
   * Filter by channel (third-level key). Requires `partition` and `collection` to be set.
   * @example 'avatars'
   */
  channel?: string

  /**
   * Maximum number of assets to return per page. Default is 25, maximum is 100.
   * @default 25
   */
  limit?: number

  /**
   * Opaque pagination cursor from a previous response. Omit for the first page.
   * @example 'eyJpZCI6ImFzc2V0XzAxSFEz...'
   */
  cursor?: string
}

/**
 * Fields that can be updated on an existing asset.
 *
 * @example
 * ```typescript
 * const updated = await imgbt.update('asset_01HQ3...', {
 *   metadata: { userId: '456', status: 'active' },
 *   tags: ['profile', 'employee', 'verified'],
 * })
 * ```
 */
export interface UpdateOptions {
  /**
   * Replaces the entire metadata object. Omit to leave metadata unchanged.
   * @example { userId: '456', status: 'active' }
   */
  metadata?: Record<string, string>

  /**
   * Replaces the entire tags array. Omit to leave tags unchanged.
   * @example ['profile', 'employee', 'verified']
   */
  tags?: string[]
}

/**
 * Image and PDF transformation parameters for URL generation.
 * All parameters are optional — omit any you don't need.
 *
 * Parameter names here are TypeScript-friendly; they are automatically
 * mapped to the shorter query-param form in the URL (e.g. `width` → `w`).
 *
 * @example
 * ```typescript
 * const url = imgbt.url('acme-corp/sf-office/avatars/jane.png', {
 *   width: 200,
 *   height: 200,
 *   fit: 'cover',
 *   format: 'webp',
 *   quality: 80,
 * })
 * // → https://assets.myapp.com/acme-corp/sf-office/avatars/jane.png?w=200&h=200&fit=cover&f=webp&q=80
 * ```
 */
export interface TransformOptions {
  /**
   * Output width in pixels.
   * @example 300
   */
  width?: number

  /**
   * Output height in pixels.
   * @example 300
   */
  height?: number

  /**
   * Resize fit mode. Controls how the image is resized to fit the given dimensions.
   * - `cover` — crop to fill (default when both w and h are set)
   * - `contain` — letterbox / maintain aspect ratio
   * - `fill` — stretch to exact dimensions
   * - `inside` — scale down to fit within dimensions, never scale up
   * - `outside` — scale up to fill dimensions, never scale down
   *
   * @example 'cover'
   */
  fit?: 'cover' | 'contain' | 'fill' | 'inside' | 'outside'

  /**
   * Output image format. Overrides auto-format negotiation.
   * - `webp` — best compression for modern browsers
   * - `avif` — next-gen format, best compression
   * - `png` — lossless, best for screenshots/graphics
   * - `jpg` — lossy, best for photos
   * - `gif` — animated images
   *
   * @example 'webp'
   */
  format?: 'webp' | 'avif' | 'png' | 'jpg' | 'gif'

  /**
   * Compression quality from 1 (lowest) to 100 (highest).
   * Applies to lossy formats (webp, avif, jpg). Ignored for lossless (png, gif).
   *
   * @example 80
   */
  quality?: number

  /**
   * Apply Gaussian blur. Value from 1 (subtle) to 100 (extreme).
   * @example 10
   */
  blur?: number

  /**
   * Apply sharpening. Value from 1 (subtle) to 100 (extreme).
   * @example 5
   */
  sharpen?: number

  /**
   * Rotate the image clockwise by the given number of degrees.
   * Common values: 90, 180, 270.
   *
   * @example 90
   */
  rotate?: number

  /**
   * Flip the image horizontally (`h`) or vertically (`v`).
   * @example 'h'
   */
  flip?: 'h' | 'v'

  /**
   * Convert the image to grayscale.
   * @example true
   */
  grayscale?: boolean

  /**
   * Add a border. Format: `{width},{hex_color}` — width in pixels, color without `#`.
   * @example '5,ff0000'
   */
  border?: string

  /**
   * Round the corners of the image. Provide a pixel radius or `'max'` for a circle/pill.
   * @example 20
   * @example 'max'
   */
  radius?: number | 'max'

  /**
   * Background fill color for transparent regions (e.g. when converting PNG → JPG).
   * Hex color string without `#`.
   *
   * @example 'ffffff'
   */
  bg?: string

  /**
   * Device pixel ratio multiplier. Useful for serving retina images.
   * The effective pixel dimensions are multiplied by this value.
   *
   * @example 2
   */
  dpr?: number

  /**
   * Smart crop mode. Automatically selects the most interesting crop region.
   * - `face` — centre the crop on detected faces
   * - `auto` — automatic content-aware crop
   * - `entropy` — maximise entropy / detail
   * - `attention` — focus on high-attention regions
   *
   * @example 'face'
   */
  crop?: 'face' | 'auto' | 'entropy' | 'attention'

  /**
   * Gravity / focus point for cropping and resizing.
   * - `center` — centre of the image
   * - `north` — top edge
   * - `south` — bottom edge
   * - `east` — right edge
   * - `west` — left edge
   * - `face` — detected face
   * - `auto` — automatic content-aware
   *
   * @example 'face'
   */
  gravity?: 'center' | 'north' | 'south' | 'east' | 'west' | 'face' | 'auto'

  /**
   * For PDF assets: which page to render.
   * Use a number (1-indexed), `'all'` for all pages, or a range like `'1-5'`.
   *
   * @example 1
   * @example 'all'
   * @example '1-5'
   */
  page?: number | 'all' | string
}

/**
 * Options for generating a signed URL with expiration.
 *
 * @example
 * ```typescript
 * const url = imgbt.signUrl('acme-corp/docs/contract.pdf', {
 *   expiresIn: '24h',
 * })
 * // → https://assets.myapp.com/acme-corp/docs/contract.pdf?token=xxx&expires=1707436800
 * ```
 */
export interface SignUrlOptions {
  /**
   * How long the signed URL should remain valid.
   * Accepts a number (seconds) or a human-readable string.
   *
   * Supported string formats: `'30s'`, `'5m'`, `'24h'`, `'7d'`.
   *
   * @example '24h'
   * @example '7d'
   * @example 3600
   */
  expiresIn: string | number

  /**
   * Optional password to protect the URL. When set, the recipient must enter
   * this password before the asset is served.
   *
   * @example 'secret123'
   */
  password?: string
}

/**
 * A paginated list result. Returned by `imgbt.list()`.
 *
 * Can be iterated manually using `result.data` and `result.cursor`,
 * or automatically with `for await`:
 *
 * @example
 * ```typescript
 * // Manual pagination
 * const page1 = await imgbt.list({ partition: 'acme-corp', limit: 50 })
 * console.log(page1.data)       // Asset[]
 * console.log(page1.hasMore)    // boolean
 * console.log(page1.cursor)     // string | null
 *
 * // Auto-pagination via async iterator
 * for await (const asset of imgbt.list({ partition: 'acme-corp' })) {
 *   console.log(asset.filename)
 * }
 * ```
 */
export interface ListResult<T> extends AsyncIterable<T> {
  /** The assets on the current page */
  data: T[]

  /**
   * Opaque cursor to pass as `cursor` in the next `list()` call.
   * `null` when there are no more pages.
   */
  cursor: string | null

  /**
   * Whether there are more pages after this one.
   * When `false`, `cursor` is `null`.
   */
  hasMore: boolean
}

/**
 * Raw paginated API response envelope returned by the server.
 * @internal
 */
export interface PaginatedResponse<T> {
  data: T[]
  cursor: string | null
  has_more: boolean
}

/**
 * Raw asset shape as returned by the API (snake_case).
 * @internal
 */
export interface RawAsset {
  id: string
  vault: string
  partition: string
  collection: string
  channel: string
  filename: string
  url: string
  path: string
  content_type: string
  size: number
  width?: number
  height?: number
  pages?: number
  metadata: Record<string, string>
  tags: string[]
  created_at: string
  updated_at: string
}
